# Generated by Django 2.1 on 2021-06-20 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 2, 24, 24, 557882, tzinfo=utc)),
        ),
    ]
